#===========================================
#   Server
#===========================================
server:
  port: 20000
  servlet:
    context-path: /
    session:
      # 8小时
      timeout: 28800
  shutdown: graceful
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: false

#===========================================
#   Spring
#===========================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db0?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    druid:
#      url: jdbc:mysql://localhost:3306/db0?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
  servlet:
    multipart:
      max-file-size: 1GB
  lifecycle:
    timeout-per-shutdown-phase: 60s
  profiles:
    active: local

#===========================================
#   MyBatis
#===========================================
mybatis:
  mapper-locations: classpath:mapper/**
  type-aliases-package: com.gyoomi.mybatis.defaults.model