#===========================================
#   Server
#===========================================
server:
  port: 20000
  servlet:
    context-path: /
    session:
      # 8小时
      timeout: 28800
  shutdown: graceful
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: false

#===========================================
#   Spring
#===========================================
spring:
#  datasource:
#    dynamic:
#      druid:
#        initial-size: 2
#        max-active: 20
#        test-on-borrow: true
#        validation-query: SELECT now()

  servlet:
    multipart:
      max-file-size: 1GB
  lifecycle:
    timeout-per-shutdown-phase: 60s
  profiles:
    active: local

#===========================================
#   MyBatis
#===========================================
mybatis:
  mapper-locations: classpath:mapper/**
  type-aliases-package: com.gyoomi.multipledatasource.mybatis.hikari.model
